### ISSUE TITLE
need for a dedicated prebuilt images (hyperkube, hetzner-netconf)

### ISSUE THREAD

**Issue by upolymorph** [cornelius-keller/ansible-coreos-kubernetes#5]
From a security point of view, why do we need a dedicated/homebuilt hyperkube image (quay.io/cornelius/hyperkube). Shouldn't we explain teh goal and potentially document a way to built this hyperkube image from scratch?  Also is it normal that there is different hyperkube (from new inventory ini file) version hardcoded in the cloud_config.tmpl (for ex. line 59)?

**Comment by cornelius-keller** [comment]
HI @upolymorph, 

this image was needed because the coreos stock ones were missing some binaries for example for ceph usage etc.
From a security point of view you can bring your own very easily if you don't trust this one.

The hetzner netconf one is a tricky one. Hetzner puts every host in its own vlan. But it also subnets the hosts into subnets which are bigger then the vlan. This is fine as long as you don't have two hosts in the same subnet. Then there are no arp requests possible due to the vlan, but also no routes to the other hosts in the subnet. The hetzner-netconf image solve this by adding dedicated routes to every host in the subnet.

Line 59 is a bug. It is not severe because only kubectl is needed here which is compatible for some versions. But I will replace it by the inventory image and tag.

**Comment by upolymorph** [comment]
I can correct the the tmpl file and propose it during a PR.
can you provide us with the Docker file for cornelius/hyperkube and netconf? for netconf why don't we use a task to setup routes on each nodes?

**Comment by cornelius-keller** [comment]
https://github.com/cornelius-keller/hetzner-netconf

**Comment by cornelius-keller** [comment]
I did not use a task because you have to determine the network configuration and calculate subnet masks etc. Essentially the image is executing a python script, having it in a container is just convenience.

**Comment by upolymorph** [comment]
I am stucked since 3 days in bootstrapping my first cluster and just discover that the issue is in fact related to routes in hetzner. I have one node in an other VLAN and the hetzner-netconf trick do not seems to work at least no on all nodes :-(

**Comment by cornelius-keller** [comment]
HI @upolymorph ,

I am sorry to hear this. The vlans gave me some sleepless nights to.
In hetzer every node is in a separate vlan.
If they are in different IP subnets it is no problem, the default routing will work.
The problem starts if they are in the same IP subnet. Then there are no default routs to the other nodes in the subnet, and arp does not work because of the vlan.
The hetzner netconf script tries to solve this by adding routes to all the nodes in the same subnet.
So if it was  was working you should see hostroutes for every other ip in the same subnet on every node.
Do a `route -n` to verify.

If it is not working the symtom is that some nodes don't have IP connectivity, i.e not even pings are working.

This results in strange netsplits for example for etcd.
To help you better I need more information about the Problems you are having. Maybe you have a special case were the hetzner-netconf script needs to be imporved.

**Comment by cornelius-keller** [comment]
Hi @upolymorph, I executed your master branch on my test cluster, it results in an healthy cluster in my  case.

if in do a `route -n `

i get 
```
core@core01 ~ $ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         176.9.123.225   0.0.0.0         UG    1024   0        0 enp4s0
10.1.0.0        0.0.0.0         255.255.0.0     U     0      0        0 docker0
10.1.24.0       0.0.0.0         255.255.255.0   U     0      0        0 docker0
176.9.123.224   0.0.0.0         255.255.255.224 U     0      0        0 enp4s0
176.9.123.225   0.0.0.0         255.255.255.255 UH    1024   0        0 enp4s0
176.9.123.226   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.227   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.228   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.229   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.230   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.231   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.232   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.233   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.234   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.235   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.236   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.237   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.238   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.239   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.240   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.241   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.242   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.243   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.244   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.245   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.246   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.247   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.248   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.249   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.250   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.251   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.252   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.253   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
176.9.123.254   176.9.123.225   255.255.255.255 UGH   0      0        0 enp4s0
```

if I do an ifconfig I get 

```
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.1.24.1  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::42:37ff:fe8f:c415  prefixlen 64  scopeid 0x20<link>
        ether 02:42:37:8f:c4:15  txqueuelen 0  (Ethernet)
        RX packets 15765  bytes 7189842 (6.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 15107  bytes 8090562 (7.7 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp4s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 176.9.95.22  netmask 255.255.255.255  broadcast 176.9.95.22
        inet6 fe80::5604:a6ff:feb2:9e  prefixlen 64  scopeid 0x20<link>
        ether 54:04:a6:b2:00:9e  txqueuelen 1000  (Ethernet)
        RX packets 1362775  bytes 1956895431 (1.8 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 166210  bytes 26933334 (25.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 36068  bytes 22595767 (21.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 36068  bytes 22595767 (21.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tap0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::d451:f0ff:fe99:37a7  prefixlen 64  scopeid 0x20<link>
        ether d6:51:f0:99:37:a7  txqueuelen 1000  (Ethernet)
        RX packets 4580  bytes 1284198 (1.2 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5330  bytes 4167467 (3.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth0881b21: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b88d:d4ff:fe2b:3c31  prefixlen 64  scopeid 0x20<link>
        ether ba:8d:d4:2b:3c:31  txqueuelen 0  (Ethernet)
        RX packets 1846  bytes 879748 (859.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2060  bytes 1050176 (1.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth680c1ad: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::18b4:77ff:fed8:1d0  prefixlen 64  scopeid 0x20<link>
        ether 1a:b4:77:d8:01:d0  txqueuelen 0  (Ethernet)
        RX packets 1213  bytes 110108 (107.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1308  bytes 797175 (778.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth6c7c3d2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::2cd7:6eff:feb7:c3d1  prefixlen 64  scopeid 0x20<link>
        ether 2e:d7:6e:b7:c3:d1  txqueuelen 0  (Ethernet)
        RX packets 10897  bytes 3244099 (3.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10350  bytes 3216827 (3.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethb920be9: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::e4b8:b6ff:fe34:57df  prefixlen 64  scopeid 0x20<link>
        ether e6:b8:b6:34:57:df  txqueuelen 0  (Ethernet)
        RX packets 2410  bytes 3555626 (3.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3326  bytes 671171 (655.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Can you post me the values for your cluster?

**Comment by cornelius-keller** [comment]
Hi @upolymorph,

I hope I fixed your Problem with: https://github.com/cornelius-keller/ansible-coreos-kubernetes/commit/c71c2149adb5228c28d09b5cc643ed8b5c9ee86e

Now the setting up of the subnet routes should happen before etcd tries to start.
In my case it seems it was only working because only two of the five etcd nodes were in the same subnet.

**Comment by upolymorph** [comment]
Hi @cornelius-keller 
Thanks a lot for you support ! I have tested the fix and it works; I have the route set for all my nodes. I still have issue with bootstrap process and connecting with one nodes. I am checking ... at least now the etcd cluster is healthy.

**Comment by cornelius-keller** [comment]
Hi @upolymorph,

form waht I have seen on your cluster you have sometimes comments with '#' in the inventory that are not in the beginning of the line. I think this is not supported by the .ini file format and might be causing some problems.

**Comment by upolymorph** [comment]
Yes you are right. I have modified it and get something more or less working;
- the playbook finished without error.
- only locksmithd.service is failing unit.
- kubectl get cs show me an unhealthy etcd-0 with an issue tls:bad certificate. but if I connect to nodes then I can check that etcdctl cluster-health return healthy.

**Comment by upolymorph** [comment]
This issue ca be closed as I have been able to perform a full play of teh playbook. I proposed in a PR to add images folder with link to depending images.
